name: FNA build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: libs/source/FNA
        submodules: recursive
    
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8'

    - name: dotnet build FNA.Core
      run: dotnet build -c Release FNA.Core.csproj